# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0004_auto_20161101_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='airbnb_confirmation_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='airbnb_group_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='airbnb_guest_checkin_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='airbnb_number_of_guests',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='airbnb_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='airbnb_thread_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='airbnb_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
