# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0005_auto_20161101_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='airbnb_confirmation_code',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
