# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0006_auto_20161101_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='car',
            field=models.BooleanField(default=False),
        ),
    ]
