# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0007_reservation_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='car',
            field=models.NullBooleanField(),
        ),
    ]
