# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0009_auto_20161103_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='last_sync',
            field=models.DateTimeField(default=datetime.date(2016, 9, 1)),
            preserve_default=False,
        ),
    ]
