# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0010_reservation_last_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2016, 11, 3)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
