# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0011_auto_20161103_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='car',
            new_name='has_car',
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('Airbnb', 'Airbnb'), ('Rent', 'Rent'), ('Website', 'Website')], max_length=9),
        ),
    ]
