# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0012_auto_20161103_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='airbnb_start_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('Airbnb', 'Airbnb'), ('Rent', 'Rent'), ('Website', 'Website')], max_length=9, null=True),
        ),
    ]
