# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0013_auto_20161103_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
