# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0014_auto_20161121_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payout_amount',
            field=models.FloatField(null=True),
        ),
    ]
