# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0015_auto_20161127_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paid_amount',
            field=models.FloatField(null=True),
        ),
    ]
