# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20161127_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default='2015-10-01'),
        ),
    ]
